const filters = [
  "Art & Creativity",
  "Music",
  "Technology & Coding",
  "Health & Fitness",
  "Movies & TV Shows",
  "Books & Writing",
  "Food & Cooking",
  "Adventure & Travel",
  "Cultural",
  "Social Justice & Activism",
  "Entrepreneurship & Startups",
  "Science & Research",
  "Gaming",
  "Parenting & Family",
  "Pet Lovers",
  "Education",
  "Fashion & Style",
  "Faith & Spirituality",
  "Environment & Sustainability",
  "Comedy & Entertainment",
  "DIY & Makers",
  "Dance",
  "Wellness & Self-Improvement",
  "Finance & Investing",
  "Sports Fanatics",
  "Collectors",
  "Hobbies & Interests",
  "History Buffs",
  "Outdoor Enthusiasts",
  "Photography",
  "Local Community",
  "Support & Recovery",
];
export default filters;